services:
  web:
    build: 
      context: ./ssti-demo-app
      args:
        - FLAG
    ports:
      - "60076:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
