services:
  libraryv1:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "60096:80"
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:80/')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
