services:
  web:
    build:
      context: ./vulnerable-app
    ports:
      - "60009:80"
    env_file:
      - .env
    volumes:
      - ./flag.txt:/flag.txt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      timeout: 1s
      retries: 5
      interval: 10s